#!/usr/bin/env bash

bc_asm_file=$1;
bc_mc_file=${bc_asm_file:0:-2}".mc";
bc_disasm_file=${bc_asm_file:0:-2}".dis";

# Clear build directory
echo "------------------------"
echo "Cleaning build directory"
echo "------------------------"
eval "make clean"

# Build basiccore asm program
echo ""
echo "-----------------------------------"
echo "Building basiccore assembly program"
echo "-----------------------------------"
eval "python2.7 tools/assemble.py -i bc_src/$bc_asm_file | tee bc_build/$bc_mc_file"
# Check if basiccore program assembled successfully
if [ "$?" -ne 0 ] 
then
    exit
fi
echo ""
eval "python2.7 tools/disassemble.py -i bc_build/$bc_mc_file | tee bc_build/$bc_disasm_file"

# Build basiccore simulator
echo ""
echo "----------------------------"
echo "Building basiccore simulator"
echo "----------------------------"
eval "cp Makefile build/"
eval "cp src/* build/"
eval "sed -i '/insert program here/ r bc_build/$bc_mc_file' build/main.c"
eval "cd build && make debug"
# Check if simulator compiled succesfully
if [ "$?" -ne 0 ] 
then
    exit
fi

# Run simulator
echo ""
echo "-----------------"
echo "Running simulator"
echo "-----------------"
eval "./basiccore"
    


